<?php

// This file is auto-generated by FactoryStubGenerator
// Copy this file to your project root as .phpstorm.meta.php
// Or include it in your existing .phpstorm.meta.php file
// Run: composer generate-stubs to regenerate

namespace PHPSTORM_META {

    // Enable fluent interface autocomplete for factory methods
    override(\Algoritma\ShopwareTestUtils\Factory\AbstractFactory::__call(0), type(0));

}
