<?php
/**
 * Autogenerated Configuration. DO NOT EDIT.
 */
$autoloadPathProvider = new Algoritma\CodingStandards\AutoloadPathProvider();

$additionalRules = [];
$rulesProvider = new Algoritma\CodingStandards\Shared\Rules\CompositeRulesProvider([
    new Algoritma\CodingStandards\Phpstan\Rules\PhpstanRulesProvider(),
    new Algoritma\CodingStandards\Shared\Rules\ArrayRulesProvider($additionalRules),
]);

/**
 * Paths need to be absolute only on PHP Configuration.
 */
$paths = array_map(
    static function(string $path) {
        return \Symfony\Component\Filesystem\Path::makeAbsolute($path, __DIR__);
    }, $autoloadPathProvider->getPaths());

$paths = array_values(array_unique($paths));

return [
    'parameters' => [
        'paths' => $paths,
        'treatPhpDocTypesAsCertain' => false,
        'inferPrivatePropertyTypeFromConstructor' => true,
        'type_perfect' => [
            'no_mixed_property' => true,
            'no_mixed_caller' => true,
            'null_over_false' => true,
            'narrow_param' => true,
            'narrow_return' => true,
        ],
        'errorFormat' => 'ticketswap',
        'editorUrl' => 'phpstorm://open?file=%%file%%&line=%%line%%',
    ],
    'rules' => $rulesProvider->getRules()
];
