<?php

declare(strict_types=1);

namespace Algoritma\ShopwareTestUtils\Tests\Core;

use Algoritma\ShopwareTestUtils\Core\DalMetadataService;
use Algoritma\ShopwareTestUtils\Core\FactoryStubGenerator;
use Algoritma\ShopwareTestUtils\Factory\AbstractFactory;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class FactoryStubGeneratorTest extends TestCase
{
    private string $tempDir;

    private DalMetadataService&MockObject $metadataService;

    private string $projectRoot;

    protected function setUp(): void
    {
        $this->projectRoot = dirname(__DIR__ . '/_fixtures/App');
        $this->tempDir = sys_get_temp_dir() . '/factory-stub-test-' . uniqid('', true);
        mkdir($this->tempDir, 0o777, true);
        mkdir($this->tempDir . '/tests', 0o777, true);

        $this->metadataService = $this->createMock(DalMetadataService::class);
        $this->metadataService->method('getEntityProperties')
            ->willReturn([
                'name' => ['name' => 'name', 'php_type' => 'string'],
                'active' => ['name' => 'active', 'php_type' => 'bool'],
            ]);
        $this->metadataService->method('getEntityRelations')
            ->willReturn([
                'category' => ['name' => 'category', 'reference_class' => 'CategoryEntity'],
            ]);
    }

    protected function tearDown(): void
    {
        if (is_dir($this->tempDir)) {
            $this->removeDirectory($this->tempDir);
        }
    }

    public function testGenerateCreatesStubFile(): void
    {
        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir);

        $this->assertArrayHasKey('stub', $result);
        $this->assertArrayHasKey('meta', $result);
        $this->assertFileExists($result['stub']);
        $this->assertFileExists($result['meta']);
    }

    public function testGenerateStubFileContainsExpectedContent(): void
    {
        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir . '/tests');

        $stubContent = file_get_contents($result['stub']);

        $this->assertStringContainsString('<?php', $stubContent);
        $this->assertStringContainsString('This file is auto-generated by FactoryStubGenerator', $stubContent);
        $this->assertStringContainsString('namespace Algoritma\ShopwareTestUtils\Factory', $stubContent);
        $this->assertStringContainsString('class ProductFactory', $stubContent);
    }

    public function testGenerateMetaFileContainsExpectedContent(): void
    {
        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir . '/tests');

        $metaContent = file_get_contents($result['meta']);

        $this->assertStringContainsString('<?php', $metaContent);
        $this->assertStringContainsString('This file is auto-generated by FactoryStubGenerator', $metaContent);
        $this->assertStringContainsString('namespace PHPSTORM_META', $metaContent);
        $this->assertStringContainsString('override', $metaContent);
    }

    public function testGenerateReturnsCorrectPaths(): void
    {
        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir . '/tests');

        $expectedStubPath = $this->tempDir . '/tests/factory-stubs.php';
        $expectedMetaPath = $this->tempDir . '/tests/.phpstorm.meta.php';

        $this->assertSame($expectedStubPath, $result['stub']);
        $this->assertSame($expectedMetaPath, $result['meta']);
    }

    public function testGenerateHandlesEmptyFactoryDirectory(): void
    {
        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir . '/tests');

        $this->assertFileExists($result['stub']);
        $this->assertFileExists($result['meta']);

        $stubContent = file_get_contents($result['stub']);
        $this->assertStringContainsString('namespace Algoritma\ShopwareTestUtils\Factory', $stubContent);
    }

    public function testGenerateOverwritesExistingFiles(): void
    {
        $stubPath = $this->tempDir . '/tests/factory-stubs.php';
        $metaPath = $this->tempDir . '/tests/.phpstorm.meta.php';

        file_put_contents($stubPath, 'old content');
        file_put_contents($metaPath, 'old content');

        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir . '/tests');

        $stubContent = file_get_contents($result['stub']);
        $metaContent = file_get_contents($result['meta']);

        $this->assertStringNotContainsString('old content', $stubContent);
        $this->assertStringNotContainsString('old content', $metaContent);
        $this->assertStringContainsString('auto-generated', $stubContent);
        $this->assertStringContainsString('auto-generated', $metaContent);
    }

    public function testGenerateIncludesDeclaredFactories(): void
    {
        $generator = new FactoryStubGenerator($this->metadataService, $this->projectRoot);

        $result = $generator->generate($this->tempDir . '/tests');

        $stubContent = file_get_contents($result['stub']);

        $this->assertStringContainsString('namespace Algoritma\ShopwareTestUtils\Factory {', $stubContent);
        $this->assertStringContainsString('class ProductFactory', $stubContent);
    }

    private function removeDirectory(string $dir): void
    {
        if (! is_dir($dir)) {
            return;
        }

        $files = array_diff(scandir($dir), ['.', '..']);
        foreach ($files as $file) {
            $path = $dir . '/' . $file;
            is_dir($path) ? $this->removeDirectory($path) : unlink($path);
        }
        rmdir($dir);
    }
}

class DeclaredTestFactory extends AbstractFactory
{
    protected function getRepositoryName(): string
    {
        return 'product.repository';
    }

    protected function getEntityName(): string
    {
        return 'product';
    }

    protected function getDefaults(): array
    {
        return [];
    }
}
